language: bash
script:
  - pwd
branches:
only:
- master

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "233mac"
  - git config --local user.email "service@233mac.com"
  - export TRAVIS_TAG=$(git log --format=%h -1)
  - echo $TRAVIS_TAG
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  skip_cleanup: true
  on:
      tags: true
